In [2]:
import numpy as np

arr_1=np.full((3, 4), 3, dtype=int)
print(arr_1)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [3]:
arr_2 = np.random.randint(0, 9, (2, 4))
print(arr_2)

[[2 7 0 8]
 [3 8 1 0]]


In [4]:
print(arr_1.size, arr_2.size)

12 8


In [94]:
print(np.concatenate([arr_1, arr_2], axis=0 ))

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [7 0 6 4]
 [0 6 5 5]]


In [95]:
arr_3=np.array((1, 8, 6, 5, 8, 3))
print(arr_3)

[1 8 6 5 8 3]


In [96]:
arr_4=arr_3*3+1
print(arr_4)

[ 4 25 19 16 25 10]


In [97]:
arr_5=arr_3.reshape(2,3)
print(arr_5)

[[1 8 6]
 [5 8 3]]


In [98]:
arr_5.min(axis=1)

array([1, 3])

In [99]:
print(np.sum(arr_5)/arr_5.size)

5.166666666666667


In [5]:
arr_6=np.arange(11)
arr_6=arr_6**2
print(arr_6)

[  0   1   4   9  16  25  36  49  64  81 100]


In [6]:
print(arr_6[1::2])

[ 1  9 25 49 81]


In [7]:
print(arr_6[::-1])

[100  81  64  49  36  25  16   9   4   1   0]


In [8]:
for i in range(arr_6.size):
    if np.any(arr_6[1::2]==arr_6[i]):
        arr_6[i]=2
print(arr_6)

[  0   2   4   2  16   2  36   2  64   2 100]


In [9]:
print(np.any(arr_6==49))

False


In [105]:
b=[]
a=np.random.randint(-10, 10, (2, 10))
for i in range(a.ndim):
    for j in range(a.shape[1]):
        if a[i][j]<0:
            b.append(a[i][j])
b=np.array(b)
print(b)

[ -5  -1  -6 -10  -4  -7 -10  -1  -8  -1  -2]
